server:
  port: 8082
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:marinha
    username: sa
    password:
    driverClassName: org.h2.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    request:
      exchenge:
        producer: ex.producer.marinha
      routing-key:
        producer: rk.producer.aeronave
      dead-letter:
        producer: dl.producer.aeronave
      parking-lot:
        producer: pl.producer.aeronave
    listener:
      time-retry: 00 39 22 * * *